### ISSUE TITLE
wufuc is injecting into the wrong svchost.exe process because there are multiple netsvcs instances running

### ISSUE THREAD

**Issue by felipaopl** [zeffy/wufuc#103] opened 2017-08-24 08:06 UTC
[wufucrundll32exe.txt](https://github.com/zeffy/wufuc/files/1248124/wufucrundll32exe.txt)
[wufucsvchostexe.txt](https://github.com/zeffy/wufuc/files/1248125/wufucsvchostexe.txt)

We're applying SCCM images to our new workstations here with Windows 7 patched up to July's monthly rollup. After the image process finishes, everything looks fine and wufuc is correctly installed, but we keep getting the "hardware incompatibility" pop-up window (logs attached).

Tried to reinstall it using the latest version and the "beta" versions available, no dice. Kaby Lake processor, 7th gen, wuaueng.dll ver 7.6.7601.23806.

Thanks for the tool and support!

**Comment by zeffy** [comment] 2017-08-24 08:20
That's really odd, according to the log file wuaueng.dll isn't getting loaded into the netsvcs `svchost.exe` process.

Would it be possible for you to:

1. Open Task Manager on the machine this is happening on
2. Go to the Processes tab, select the View menu and choose Select columns, then check "Command Line" near the bottom and press OK
3. Then go to the Services tab, find `wuauserv` and right click it, then select "Go to process"

Can you tell me what it says under the "Command Line" column for that process? 

Thank you for reporting this issue!

**Comment by felipaopl** [comment] 2017-08-24 23:39
Thanks mate, sorry for taking so long. It lists svchost's path:
C:\Windows\System32\svchost.exe -k netsvcs

**Comment by zeffy** [comment] 2017-08-25 00:16
That's very weird...

Could you try stopping and starting the `wuauserv` service from the Task Manager with wufuc enabled, 
and then upload the logs again? Also check to see if it Windows Update starts working after that.

Additionally, is there anything else you can tell me about your setup that would differ from a normal install of Windows? The more information I have to work with, the better.

Thanks again.

**Comment by felipaopl** [comment] 2017-08-25 00:29
Thanks, just restarted it with wufuc enabled, same outcome - Windows Update has a warning with a button "Check for Updates", and the popup appears almost instantly after clicking on it. It tries to do its thing for a few minutes and then stops with 80240037 error (unsupported hardware according to MS docos).

New logs attached
[wufuc.rundll32.exe.txt](https://github.com/zeffy/wufuc/files/1250539/wufuc.rundll32.exe.txt)
[wufuc.svchost.exe.txt](https://github.com/zeffy/wufuc/files/1250540/wufuc.svchost.exe.txt)

Nothing really different from a normal install besides Windows Update linked to a WSUS server (but tried via Internet, same issue), a few CAD applications built-in, and also a proxy server.

**Comment by zeffy** [comment] 2017-08-25 23:58
This is so strange... if I had to venture a guess what was happening, it is probably either:

1. wufuc is injecting itself into the wrong `svchost.exe` process, except this doesn't make sense because as you say, wuauserv is running in `netsvcs`, which is what it was injecting into, or
2. It could be possible that `wuauserv` is getting loaded with some other API than `LoadLibraryEx` which wufuc isn't hooking.

I'm hoping its the latter... I'm going try to throw together a beta version that hooks some other APIs that it could be using, and see if it fixes it. Will comment again when it's ready.

**Comment by zeffy** [comment] 2017-08-27 13:52
Okay, so unless I'm completely wrong about what is happening here (let's hope not!), I think I may have found a solution. 

I've spent that last couple days rewriting a large portion of wufuc's code base so that I could use a much lower level hook (using the undocumented NT API `LdrRegisterDllNotification`), which will catch every single DLL loaded into the `svchost.exe` process that wufuc injects itself into, and not just ones loaded specifically by `LoadLibraryEx`.

It's not completely done yet, but I should be able to push the changes some time tomorrow so that you can test it out and see if it works or not. If it still doesn't work, then I'll have to explore other avenues and may need you to gather some additional information from your machine so that I can figure out what is going on.

I'll comment here again when the changes are live.

**Comment by rautamiekka** [comment] 2017-08-27 14:44
^
>(using the undocumented NT API LdrRegisterDllNotification)

Doesn't look undocumented to me when there are 2 links to MSDN in Google results as the first 2 hits and MSDN is pretty nicely cataloging it: https://msdn.microsoft.com/en-us/library/dd347461(v=vs.85).aspx

**Comment by zeffy** [comment] 2017-08-27 20:30
@rautamiekka Yes, the function itself may technically be "documented" (as in, it is cataloged on MSDN), but it is still considered undocumented as per:

> [This function may be changed or removed from Windows without further notice.]

and 

>This function has no associated header file. The associated import library, Ntdll.lib, is available in the WDK. You can also use the LoadLibrary and GetProcAddress functions to dynamically link to Ntdll.dll.

This means the function and the corresponding struct types it uses are not included in any headers and you have to resort to other trickery to even use the function. 

For example, try finding documentation on MSDN for the `PLDR_DLL_NOTIFICATION_FUNCTION` struct referred to on that page you linked. You won't find it. :)

**Comment by felipaopl** [comment] 2017-08-28 01:15
Awesome zeffy, thanks for the support! Waiting on your next update.

**Comment by zeffy** [comment] 2017-08-28 02:35
@felipaopl No problem! The code changes are live as of 8052351 (click for description of changes), you can get the latest appveyor build artifacts here: 

https://ci.appveyor.com/project/zeffy/wufuc/build/0.7.2.107/job/mv0mthy4jr3t77o7/artifacts

Assuming the changes I made actually fix your problem, everything should work correctly. Either way, could you do me a favor and upload the log files from this version after you get it set up? 

Thanks again.

**Comment by felipaopl** [comment] 2017-08-28 05:13
Thanks zeffy, really appreciate your (free) commitment! Unfortunately, no dice, still the same thing. Attached logs for your appreciation. Please note that they're bigger than usual as I tried to restart the workstation after the new version was installed, and also ran the "enable" bat to make sure it was loaded.

Thanks one more time for your time mate.

[wufuc64.rundll32.exe.txt](https://github.com/zeffy/wufuc/files/1255173/wufuc64.rundll32.exe.txt)
[wufuc64.svchost.exe.txt](https://github.com/zeffy/wufuc/files/1255174/wufuc64.svchost.exe.txt)

**Comment by zeffy** [comment] 2017-08-28 06:22
No worries, always happy to help! At least this new callback method gives me a lot more information to work with.

Okay, so it would be incredibly helpful if you did the following things for me:

1. Using the same instructions I posted above to enable the "Command Line" column, could you turn on the "PID (Process Identifier)" column in the Task Manager, and check what the **command line** and **PID** are for these services, and post them here:

- wuauserv
- AeLookupSvc
- IKEEXT

2. After that, can you check what happens if you start `wuauserv` from the Task Manager services tab (if it isn't already running), and then go to wufuc's folder, navigate to the `utility scripts` sub folder, and run `disable_wufuc.bat` as administrator, then run `enable_wufuc.bat` also as administrator. Does it work if you do this? 

3. After you've done both those things, please post your logs again.

**Comment by felipaopl** [comment] 2017-08-28 07:01
Sure thing:

wuauserv - 4628
AeLookupSvc - 396
IKEEXT - 396

And yes! After manually running the disable/enable scripts from the "utility scripts" folder, it worked flawlessly. Logs attached!

PS.: it does not work, however, after a restart, and I need to perform the same procedure above. Am I required to extract the files somewhere specifically (since this isn't the advanced installer method)? I've noticed that no folder was created inside "Program Files" and I wonder if the patch is actually being loaded?

[wufuc64.rundll32.exe.txt](https://github.com/zeffy/wufuc/files/1255333/wufuc64.rundll32.exe.txt)
[wufuc64.svchost.exe.txt](https://github.com/zeffy/wufuc/files/1255332/wufuc64.svchost.exe.txt)

Cheers!

**Comment by zeffy** [comment] 2017-08-28 07:19
The .zip package is more of a "portable" installer, and it will install to wherever it is at the time you run install_wufuc.bat.

Well now I know what the problem is! It looks like there are two `svchost.exe` processes running under the `netsvcs` service group for some reason, and wufuc is attaching to the incorrect one. I've actually never encountered this before, it's pretty interesting. Usually `wuauserv` runs in the same process as those other services I listed.

The only reason it works when you specifically disable/enable wufuc while wuauserv is running, is because under normal circumstances, at system boot `wuauserv` is set to "Delay Load", which means it doesn't actually start for about 3-5 minutes after a system boot. So I usually can't just retrieve the `wuauserv` PID, since it isn't actually running when wufuc starts. 

To get around that, I had to code some logic that would "guess" which process to inject into, based on other services that are running in the same service group - usually `netsvcs`. Since I'd never seen multiple processes running under the same service group, I figured that would be fool-proof enough. Guess not!

It looks like I may have to modify the injection logic to be smarter, perhaps brute-force it by injecting into every possible `svchost.exe` that it could be running under, and then signal the extra instances to unload when the real process is discovered. I'll have to change a lot of things though, because things like the logging system and the unload event signaling depend on there only being one instance of wufuc running at any given time.

I'll have to think on this for a bit and see if I can come up with a clean solution. Thanks very much for getting back so quick!

**Comment by zeffy** [comment] 2017-08-28 07:23
Also, just out of curiosity, can you check your Task Manager and see how many `svchost.exe` processes have this command line: `C:\Windows\System32\svchost.exe -k netsvcs` ? Thanks.

**Comment by felipaopl** [comment] 2017-08-28 07:29
Interesting explanation. I wonder if the reason has anything to do with retrieving updated from an internal WSUS server instead of straight from Windows Update? Probably not, but doesn't hurt to comment. Take your time though, wish I could be more helpful here.

About the processes and the command line: only one after restarting, disabling/enabling wufuc. Two as soon as I try to run Windows Update.

**Comment by zeffy** [comment] 2017-08-28 07:44
>Interesting explanation. I wonder if the reason has anything to do with retrieving updated from an internal WSUS server instead of straight from Windows Update? Probably not, but doesn't hurt to comment.

That's actually pretty possible. I might have to set up an environment where I can test this specifically at some point.

>About the processes and the command line: only one after restarting, disabling/enabling wufuc. Two as soon as I try to run Windows Update.

Well, that complicates things. If the `svchost.exe` process that `wuauserv` is running in isn't even running at system boot, then there's no way for wufuc to "see" it. 

I might have to have wufuc inject into `services.exe` instead, and use that to automatically inject into every `svchost.exe` process that it spawns. Maybe it's possible to check if a given `svchost.exe` process will be used to host `wuauserv` or not? I will have to look into this. 

The only problem with that solution is, the consequences of my code having bugs and crashing could potentially be far more serious than if it just crashed a single non-critical `svchost.exe` process. I'll have to approach this with caution.

>Take your time though, wish I could be more helpful here.

No worries my dude; you've been incredibly helpful! I probably never would have even known about this issue or what was causing it without your help. :)

**Comment by AtakSnajpera** [comment] 2017-08-28 13:41
zeffy what do you think about this method?
https://github.com/p-lider/WuaCpuFix

**Comment by zeffy** [comment] 2017-08-28 14:21
@AtakSnajpera Interesting, I hadn't seen that project yet. I took a look at it, some things I've noticed at first glance:

- C++ :nauseated_face: 
- doesn't support x86
- copies itself to c:\windows\system32
- modifies your Windows Update service registry settings to point to his DLL instead of `wuaueng.dll`
- acts as some kind of proxy between svchost.exe and the original `wuaueng.dll` (I think?)
- hooks IsCPUSupported() and just returns 1

If you want my honest opinion, I think it is way over-engineered and changes too many system settings for what little it offers. It probably works mostly fine, though.

**Comment by AtakSnajpera** [comment] 2017-08-28 14:59
I think lack of x86 should not be a big problem. After all who does buy KabyLake/Ryzen CPU and installs 32 bit OS? 
Yes it acts as launcher for original wuaueng.dll. This way he doesn't have to guess to which svchost inject.
You mentioned earlier that you might need to inject to all svchosts. Don't you think that it is also becoming over-enginered and too intrusive?

**Comment by numpa** [comment] 2017-08-28 18:34
@AtakSnajpera 
But the problem is that not only new CPU's are not supported. I have a PC with Core i5-760 CPU and WU tells me it is also "unsupported". So IMO x86 must be supported, since more and more old processors become "unsupported".

**Comment by AtakSnajpera** [comment] 2017-08-28 19:35
Ok. I didn't know that M$ is so extremely desperated to promote Service10 OS even on older CPU. (pre-Sandy Bridge)

**Comment by zeffy** [comment] 2017-08-28 22:06
Yes, pretty much what @numpa said. Also other than that, I don't feel like it's my place to decide what people should or should not be doing with their PCs. For example, sometimes you have to use a 32-bit OS for application compatibility; I still have an isolated Windows XP machine for this reason.

>You mentioned earlier that you might need to inject to all svchosts. Don't you think that it is also becoming over-enginered and too intrusive?

I said it was an option, not necessarily what I'm going to do; just brainstorming ideas. When I do solve this issue, I will take care that it is not intrusive. Besides, injecting into a process (or processes) and modifying things in memory will always be less intrusive than something that hacks the registry and drops files in system32, IMO.

**Comment by AtakSnajpera** [comment] 2017-08-29 08:41
>  than something that hacks the registry
Well it is just single entry in HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\wuauserv\Parameters

> drops files in system32
It is just single WuaCpuFix64.dll . What is wrong in that? wufuc installer drops more files to program files ;)

In my opinion WuaCpuFix is overall simpler because:
1) unlike wufuc this method does not need scheduled task to be executed at windows start. 
2) no issues with injection to wrong svchost

And yes I've tested it and it works fine.  The only thing what is missing is logging to file like in wufuc.

**Comment by zeffy** [comment] 2017-08-29 11:37
Not to sound rude, but I'm honestly not really interested in debating the merits of either solution, and this is starting to get off topic anyway. If you think the other project is superior, you're perfectly free to use it instead.

**Comment by AtakSnajpera** [comment] 2017-08-29 12:39
Sorry I didn't want to offend you in any way. That was not my intention.

**Comment by zeffy** [comment] 2017-08-29 21:14
Don't worry, I'm not offended at all. :) I'd just rather spend my time working on solutions for the issues my project has rather than debating the semantics of someone else's.

---

Back on topic though, I did some research and it turns out on Windows 8.1, `services.exe` is a protected process and you can't mess with it without a signed kernel driver (if I understand correctly), which is what I wanted to avoid in the first place by using the injection method.

So I'm looking into other options, some seem promising. I'll comment again when I have a more clear picture how I'll make this work.

**Comment by Syping** [comment] 2017-08-30 20:45
At Windows 8.1 i could test few methods you try to use, i have VMs and Dual Boot running which gave me the Unsupported Hardware error on my Ryzen CPU. Current version worked for me but i could debug the other new ones.

**Comment by zeffy** [comment] 2017-08-30 21:37
Thanks @Syping! I'll let you know when I have something.

**Comment by zeffy** [comment] 2017-09-11 01:10
Hey all, I just wanted to give you an update on my progress. I've found two potential ways I can do away with the Task Scheduler based solution, and thus bypass this issue (and all the other outstanding issues as well) entirely:

1. Using Microsoft's own Application Compatibility framework (ironic, no?), by using a specially crafted `.sdb` file that will inject my "shim" code into `svchost.exe` automatically. This would be my preferred solution, because it would be super easy to deploy at scale. All the user would need to do is install the `.sdb` file and it would just work. The only issue with this is that actually creating an `.sdb` file that does what I need is not very well documented, and could take a while to implement.

2. Using a custom Application Verifier provider. This way works similar, but isn't as easy to deploy, and would require my DLL being dropped in system32, as well as writing to the IEFO registry key. This way is more clearly documented and would be far easier to implement.

Both of these methods work similarly in that the PE loader will automatically inject my code into `svchost.exe` very early, without the need to "guess" to find the correct process. More information about these methods can be found on Google if any of you are curious.

**Comment by felipaopl** [comment] 2017-09-11 23:55
Thanks! Looking forward to a final solution!

**Comment by zeffy** [comment] 2017-09-23 23:23
@felipaopl I haven't forgetting about you! I'm still working on potential solutions for this, but first I had a question, because I might have found a band-aid fix for you, so you can use wufuc as-is until I can push out a more complete solution:

If you open a elevated command prompt (type `cmd` in your start menu, right click and Run as administrator), and type in `sc queryex wuauserv`, what does it say after `TYPE`? `WIN32_SHARE_PROCESS` or `WIN32_OWN_PROCESS`?

Because if it says `WIN32_OWN_PROCESS`, you can execute this command: `sc config wuauserv type= share` (include the space after the =), and it will make Windows Update run in a shared process again (how it is normally), which should make it work with wufuc. You may have to restart after running the command to apply changes.

**Comment by felipaopl** [comment] 2017-09-25 23:58
Hey mate, thanks! Unfortunately I can't test it anymore, we decided to move
on to Windows 10 as we were also having issues with driver availability for
Windows 7.
Thanks for the hard work, hopefully your findings up to this point will
help other people around.

**Comment by zeffy** [comment] 2017-10-03 08:51
No worries, that's a shame about the driver availability issues though! :(

Just wanted to give another update in case anyone else following this issue:

I've successfully implemented wufuc as a custom Application Verifier provider for svchost.exe, and it is working quite well in my Windows 7 x64 test VM! I essentially had to rewrite wufuc from the ground up, which gave me the opportunity iron out some long-standing issues and quirks. I still have a few changes to make, adjust the installers, and will need to test it thoroughly in other VMs, but I think its safe to say there should be a new release some time this week, assuming I don't encounter any more obstacles.

**Comment by felipaopl** [comment] 2017-10-04 07:16
Awesome! Here's hoping this will become the "definitive version" of the
tool!

**Comment by zeffy** [comment] 2017-10-09 06:48
@Syping were you still interested in testing the new version on your VMs before I release it? Specifically Windows 8.1 64- or 32-bit. If so let me know.

**Comment by Syping** [comment] 2017-10-09 06:53
@zeffy Yea i got some time right now, got a Windows 8.1 VM ready on my AMD Ryzen system.

**Comment by zeffy** [comment] 2017-10-09 06:57
@Syping Awesome! Here you go: [wufuc_v0.8.0.0-test.zip](https://github.com/zeffy/wufuc/files/1367690/wufuc_v0.8.0.0-test.zip). 

It installs the same as previous versions, but a restart is required to activate it. Also [read this](https://github.com/zeffy/wufuc#what-to-do-if-you-get-stuck-on-a-black-screen-with-just-a-cursor-after-the-windows-boot-animation) just in case, because I haven't been able to test 8.1 very well.

**Comment by Syping** [comment] 2017-10-09 07:06
@zeffy On my August outdated Windows 8.1 i'm able to search updates and install it after install wufuc 0.8, first i had keep sure of course i could regenerate that Unsupported Hardware message with wiping the old out. After i'm on the September patches i will test again searching for updates and install some random one.

Should i test some specific scenarios/settings ?

**Comment by zeffy** [comment] 2017-10-09 07:08
Mostly what I need you to test if you can reboot/log out/log back in and check for updates without any issues (like hangs or crashes, or weird errors in Windows Update). 

Also note that there will be no .log files created in this version due to some limitations that I have yet to work around. If you want to see its debugging output you can run [DebugView](https://docs.microsoft.com/en-us/sysinternals/downloads/debugview) as administrator and ticking Capture -> Capture Global Win32.

**Comment by Syping** [comment] 2017-10-09 07:25
Everything works flawlessy, DebugView is just showing me LoadingLibraries events.

**Comment by zeffy** [comment] 2017-10-09 07:27
Great! That's how it should be. You can try stopping and starting the wuauserv service in task manager if you want to see more debug messages from during the patching process, but it sounds like everything's working perfect.

Thank you very much! :)

**Comment by Syping** [comment] 2017-10-09 07:46
**Just for fun:**

```
00000005	0.04368069	[904] hooks.c:103(LoadLibraryExW_Hook): Loaded library: c:\windows\system32\wuaueng.dll	
00000006	0.05528188	[904] hooks.c:142(LoadLibraryExW_Hook): wuaueng.dll version: 7.9.9600.18696	
00000007	0.08085357	[904] patchwua.c:61(patch_wua): Patched value a at wuaueng.dll!00007FFE09FAF1BC: 00000000
```

I'm happy that it went well :D

**Comment by zeffy** [comment] 2017-10-09 07:51
Me too! I am glad you were available to test it so quickly. 

Thanks again, man! You were incredibly helpful. :smiley:

**Comment by farag2** [comment] 2017-10-09 09:22
I'll check the new version in two days, when a new PC will be bought!

**Comment by zeffy** [comment] 2017-10-10 01:43
v0.8 has been released https://github.com/zeffy/wufuc/releases/latest

Closing this issue, but feel free to comment.

**Closed by zeffy** 2017-10-10 01:43 UTC
Labels: bug
