### ISSUE TITLE
wufuc scheduled task either isn't being set up correctly, or is failing to run at system boot

### ISSUE THREAD

**Issue by Moltresrider** [zeffy/wufuc#98] opened 2017-08-09 13:34 UTC
Getting Unsupported Hardware message on that same Sandy Bridge PC Lenovo b570 with wufuc v0.7.1.81 installed. I thought that I had an older release but when I go to download and install the one here, the installer acts as if it is the same one.

Windows 7 updated last night and now wufuc v0.7.1.81 is no longer working

**Comment by Moltresrider** [comment] 2017-08-09 15:12
No reply? :( So, you do not plan on fixing this? You are just going to leave people with this message?

**Comment by zeffy** [comment] 2017-08-09 16:25
I don't know man, I just tested the new quality rollup on Windows 7 x64 and wufuc is still working as expected:
```
08/08/17 23:57:06 [1376] core.c(145): Loaded library: c:\windows\system32\wuaueng.dll
08/08/17 23:57:06 [1376] core.c(99): Address of wuaueng.dll!IsDeviceServiceable: 000007FEDE9CF2E4
08/08/17 23:57:06 [1376] core.c(112): Patched FirstRun variable: 000007FEDEC0E948 = 00000000
08/08/17 23:57:06 [1376] core.c(147): Patched Windows Update module!
```

Like I've said in your last several issues, I need the `*.log` files in your wufuc directory to provide any meaningful assistance.

**Comment by mv75** [comment] 2017-08-10 05:11
I've got the same issue today too. Previous version was installed, the message is coming up even before installing the updates. Ok, what I've done, I installed a new sb z sound card, turned on machine, went to bios and disabled onboard sound, loaded win8.1, uninstalled the asus sound software for the onboard, the cpu check popped up, I closed it. Continued to install the sb software. Checked windows update through control panel, 3 updates were pending, the check popped up again, dismissed. Installed the latest wufuc, installed the updates, rebooted, cpu check still pops up.

**Comment by mv75** [comment] 2017-08-10 05:16
Interesting. I installed the update again because I couldn't find any .log files to upload, now there are two .log files created. I'll try and attach them with this post now.
[wufuc.zip](https://github.com/zeffy/wufuc/files/1213713/wufuc.zip)

**Comment by zeffy** [comment] 2017-08-10 05:40
@mv75 can you check for updates without getting the cpu check popping up now that the log files are being created? Because I checked them and there aren't any anomalies, everything should be patched correctly.

Also, are you using the .msi installer or the .zip? I have a feeling there is an issue with the wufuc system boot task either not being created or starting correctly with the MSI installer, but I'm not sure what the cause is yet. So if you're using the MSI, you might want to try the zip instead and see if it works.

**Comment by mv75** [comment] 2017-08-10 06:17
Seems to be working now. I used the zip. I just checked for updates again, no cpu nag screen, and it showed a defender update and 3 optional driver updates. Seems normal now. Thanks. :)

**Comment by zeffy** [comment] 2017-08-10 07:01
Glad it's working for you now. Yeah, it's a pretty strange bug. A few other people have had this happen, too. It seems that it happens randomly and usually either resolves itself with time or a reinstall. I've been busy working on other projects recently, but I'm going to look into this and see if I can resolve it soon.

**Comment by mv75** [comment] 2017-08-10 08:57
Update, it seems to not be working at all anymore now.

**Comment by Aru33** [comment] 2017-08-10 14:31
Two updates published 8-8-2017:
https://support.microsoft.com/en-us/help/4034664/windows-7-sp1-windows-server-2008-r2-sp1-update-kb4034664
https://support.microsoft.com/en-us/help/890830/remove-specific-prevalent-malware-with-windows-malicious-software-remo
If it's caused by a Windows update, it's probably one of these.

**Comment by mv75** [comment] 2017-08-11 09:07
Ok, I found something. I had uninstalled a program, and then it wasn't working yesterday. The only way to get it to work again was to run the uninstaller, then installer again. Just running the installer again didn't work, or produce the .log files. But so far so good again. Seems if it flakes, you have to uninstall, then install again. Strange that uninstalling another program made this seem to be uninstalled as well. It may be what caused it all to begin when I had first posted with having uninstalled the asus audio programs in my first post above. I'm running windows update right now as I type, no nag screen again. Only update now is just another windows defender update. So it's working.

**Comment by zeffy** [comment] 2017-08-11 17:43
@mv75 Interesting, thank you for letting me know all that, hopefully I can figure out a fix.

And to be clear, has it stopped working for you with both the MSI and zip packages?

**Comment by mv75** [comment] 2017-08-11 17:51
No, zip file only. I have not used the msi at all.

**Comment by zeffy** [comment] 2017-08-11 22:56
Okay, thank you. I will look into this.

**Comment by Moltresrider** [comment] 2017-08-12 15:21
My problem resides with the msi installer

**Comment by zeffy** [comment] 2017-10-10 01:44
@Moltresrider @mv75 v0.8 has been released, and should fix whatever was causing this issue. https://github.com/zeffy/wufuc/releases/latest

Closing, but feel free to comment.

**Comment by ZURYB** [comment] 2018-01-06 08:38
Zeffy:
The link https://github.com/zeffy/wufuc/releases/latest shows wufuc v0.7.1.81 downloads. Can't find v0.8 with binaries.

I have a problem with Windows 7 x64 latest patches (from this week) installed. Copied existing disks to a new one and used a new motherboard.

The not supported message was still shown after installing and after rebooting (never worked).

I used the wufuc v0.7.1.81 zip file and installed from cmd as administrator.
 
Testing on a LAN, not Internet connected. Windows is not activated due to hardware changes. I cannot activate until I know everything works.

Logs:
[wufuclogs.zip](https://github.com/zeffy/wufuc/files/1608602/wufuclogs.zip)

**Comment by zeffy** [comment] 2018-03-16 13:42
New version coming very soon that I think should finally fix this.

**Closed by zeffy** 2018-03-16 13:42 UTC
Labels: bug, can't reproduce
